# Constants

INTRODUCTION = """Welcome to Midnight Rider
WE'VE STOLEN A CAR. WE NEED TO GET IT HOME.
THE CAR IS SPECIAL.
THAT'S WHY THE GOVERNMENT WANTS IT.
WE CAN'T LET THEM HAVE IT.
ONE GOAL: SURVIVAL... AND THE CAR
REACH THE SAFEHOUSE BEFORE THE MAN
GON GETCHU.
"""