# Constants

INTRODUCTION = """Welcome to Midnight Rider

WE'VE STOLEN A CAR. WE NEED TO GET IT HOME.
THE CAR IS SPECIAL.

THAT'S WHY THE GOVERNMENT WANTS IT.

WE CAN'T LET THEM HAVE IT.

ONE GOAL: SURVIVAL... AND THE CAR
REACH THE SAFEHOUSE BEFORE THE MAN
GON GETCHU.
"""

CHOICES = """
    --- Your Choices ---
    A. Eat a tofu
    B. Travel ahead slowly
    C. Speed ahead at full speed
    D. Stop to refuel the gas
    E. Current Status
    Q. Quit the game
    --- 
"""

REFUEL = """-------You filled the furl tank.
-------The agents got closer.
"""

EAT_TOFU = """ -------Mmmmmm. Soybean goodness,
-------Your hunger is sated.
"""

NO_TOFU = """-------You have no tofu left. 
"""

SEVERE_HUNGER = """*******Your stomach rumbles.
*******You need to eat something quick.
"""

HUNGER = """*******Your hunger is small but manageable.
"""

ENDGAME_TEXT = [
    """The game has ended. Thanks for playing!""",      # Quit the game

    """\n\nTHE AGENTS HAVE CLOSED IN ON YOU.
THERE ARE AT LEAST 20 CARS SURROUNDING YOU.
THE LEAD CAR BUMPS YOUR PASSENGER SIDE.
YOU MANAGE TO CORRECT YOUR STEERING
TO KEEP YOU FROM CRASHING.

YOU DIDN'T SEE THE AGENT'S CAR RIGHT BESIDE YOU.
THAT DRIVER BUMPS YOUR CAR.
AND THAT'S IT.

YOU SPIN UNCONTROLLABLY. 
YOUR CAR FLIPS OVER AT LEAST TWO TIMES.
OR MORE... YOU SEEM TO HAVE LOST COUNT.

SIRENS.

"ARE THEY ALIVE?" THEY SAY AS YOU HEAR
FOOTSTEPS COMING CLOSER. 
"DOESN'T MATTER, ALL WE WANTED WAS THE CAR."
YOU SEE A DOG SLOWLY STEP OUT OF THE OVERTURNED CAR. 

"YOU WILL NEVER STOP THE REVOLUTION!"
THE DOGS SEEMS TO SAY TO THE AGENTS.

IT WAS IN THE CAR THE WHOLE TIME.

YOU DRIFT OFF INTO UNCONSCIOUSNESS...

---GAME OVER---\n
""",      # Lose - Agents have caught up

    """\n\nYOU CAR SPUTTERS AND SEEMS TO LET OUT A BIG SIGH. 
THERE'S NO MORE FUEL LEFT.
    
THE AGENTS SURROUND YOU AND STEP OUT OF THEIR CARS.
THE LEAD AGENTS RIPS THE DOOR OPEN AND THROWS YOU OUT OF YOUR CAR.

"WE FINALLY GOT IT."

YOU FAILED.
""",      # LOSE - Runs out of fuel/charge

    """\n\nYOU BEGIN TO LOSE FOCUS AND THE ROAD SEEMS TO BE MIRRORED.
YOU CAN NO LONGER LIFT UP YOUR ARMS.
YOUR STOMACH HAS A WEIRD SENSATION AND RUMBLES. 
YOU ARE FAMISHED.
YOU BEGIN TO DAZE OFF AND PULLS YOUR FOOT OFF THE GAS PEDAL

THE AGENTS SURROUND YOU AND STEP OUT OF THEIR CARS. 
THE LEAD AGENTS JUMPS ONTO YOUR CAR AND RIPS THE TOP OPEN 
AND THROWS OUT OF YOUR CAR.

"WE FINALLY GO IT."

YOU FAILED.

---GAME OVER---\n
""",       # Lose - Too hungry

    """\n\nYOU PRESSED THE BUTTON TO OPEN THE GATE.
THIS ISN'T THE FIRST TIME YOU'VE DONE THIS.
YOU CAN TIME IT PERFECTLY SO THAT YOU CAN 
SLIDE THE CAR IN AS THE GATE CLOSE.

YOU KNOW YOU DID THE WRITE THING.
THE GOVERNMENT WOULD HAVE TORN THE CAR APART
ANALYZING IT, TESTING IT, THEN DESTROYING IT.

THEY DON'T KNOW ITS SECRETS...
THAT IT HOLDS THE KEY TO DIFFERENT WORLDS

AS YOU STEP OUT OF THE VEHICLE,
FIDO RUNS UP TO YOU.
"THANK YOU FOR SAVING ME."

AS YOU TAKE A COUPLE STEPS AWAY FROM THE CAR, 
IT MAKES A STRANGE NOISE.

BEFORE YOUR EYES, IT SHIFTS ITS SHAPE.
YOU HAVE SEEN THIS BEFORE, BUT ONLY IN THE MOVIES,

"BUMBLEBEE...?"

---GAME OVER---\n
"""  # WIN
]
